### ISSUE TITLE
Menu items don't bring you to the top of the page

### ISSUE THREAD

**Issue by Jaybomb** [daradermody/iigl#38] opened 2018-03-23 07:51 UTC
# Symptom
- Menu items don't bring you to the top of the page

# Steps
- Go to Wall of Fame
- Select Rocket League and wait for image to load
- Scroll to bottom of page
- Click on Register

# Result
- After folloing the steps you'll be at the bottom of the register page rather than the top

**Comment by daradermody** [comment] 2018-03-23 09:03
Duplicate of #11

**Closed** 2018-03-23 17:06 UTC
Labels: duplicate
