### ISSUE TITLE
Registration: Password Match Only Triggers On "Confirm Password" field

### ISSUE THREAD

**Issue by Jaybomb** [daradermody/iigl#35] opened 2018-03-22 19:03 UTC
# Symptoms
- Red outline remains around "Confirm Password" field if an offending character is removed from "Password" field which makes the passwords match.
- Clicking "Register" displays "The form is not complete" even though it should be considered valid

# Steps
- Company Email: jaybopper@hotmail.com
- Battlefy Username: rebulah
- Password: wasdd
- Confirm Password: wasd
- Games Selected: LoL, OW, HS
 - Remove last character from "Password" field
- Clicked “Register”

**Comment by daradermody** [comment] 2018-03-22 19:05
This looks like a duplicate of #8

**Comment by Jaybomb** [comment] 2018-03-22 20:37
Yeah basically the validation needs to trigger regardless of which of the password fields is modified.
#8 is closed but the symptoms are still present...?

**Comment by daradermody** [comment] 2018-03-23 00:08
The version with the fix hasn't been deployed to the server yet.

**Comment by Jaybomb** [comment] 2018-03-23 07:41
Ah :)

**Closed** 2018-03-23 17:05 UTC
Labels: duplicate
